= Упрощённый выпуск сертификата

В данном разделе документации описан сценарий упрощённого выпуска облачного сертификата НЭП с подтверждением через ЕСИА. Для подтверждения необходимо обязательное наличие подтвержденной учетной записи Госуслуги.

.Чтобы выпустить сертификат по упрощённой процедуре:
. Создайте и заполнить заявку на выпуск сертификата.
.. Создайте заявку на выпуск сертификата.
.. Добавьте подтверждающий документ в заявку.
. Загрузите скан подтверждающего документа.
+
NOTE: Загружать реальные сканы документов не требуется, но необходим любой "заместитель", например, черная точка размером 1х1 пиксель.
+
. Создайте запрос на подтверждение выпуска сертификата с подтверждением в ЕСИА.

[source,csharp]
----
var snils = GetReceivingCertificateEmployeeSnils();
var result = issuesService.SendReleaseStatementWithEsia(GetIssueId(), employee, snils);
if (result.Success)
 throw new ApplicationException(result.Message);
----

После подтверждения выпуска сертификата пользователем в кабинете Госуслуги, он будет выпущен
в {uc}. Загрузить выпущенный сертификат в карточку сотрудника нужно стандартным методом
`DownloadCertificateAndAssignToEmployee`.

== Подписание сертификатом {uc}

Подписание с помощью сервиса облачного подписания Контур осуществляется с помощью методов, определённых в сервисе `xref:api-description.adoc[DocsVision.Kontur.DssService.ObjectModel.Services.IKonturDssService]`.
