= Упрощённый выпуск сертификата

В данном разделе документации описан сценарий упрощённого выпуска облачного сертификата НЭП с подтверждением через ЕСИА. Для подтверждения необходимо обязательное наличие подтвержденной учетной записи Госуслуги.

.Чтобы выпустить сертификат по упрощённой процедуре:
. Создайте и заполнить заявку на выпуск сертификата.
.. Создайте заявку на выпуск сертификата.
.. Добавьте подтверждающий документ в заявку.
. Загрузите скан подтверждающего документа.
+
NOTE: Загружать реальные сканы документов не требуется, но необходим любой "заместитель", например, черная точка размером 1х1 пиксель.
+
. Создайте запрос на подтверждение выпуска сертификата с подтверждением в ЕСИА.

[source,csharp]
----
var snils = GetReceivingCertificateEmployeeSnils();
var result = issuesService.SendReleaseStatementWithEsia(GetIssueId(), employee, snils);
if (result.Success)
 throw new ApplicationException(result.Message);

<.>

public interface IKonturIssuesService <.>
{

 OperationResult<Guid> CreateCertificateIssue(StaffEmployee employee, string inn); <.>

 OperationResult<string> AddDocumentRequisites(Guid issueId, IdentityDocument passData); <.>

 OperationResult<string> SendDocumentScan(Guid issueId, SendingFileInfo fileInfo, DocumentType documentType); <.>

 OperationResult<string> SendReleaseStatement(Guid issueId); <.>

 OperationResult<string> SendReleaseStatementWithEsia(Guid issueId, StaffEmployee employee, string snils); <.>

 OperationResult<string> SignReleaseStatement(Guid issueId, string smsCode); <.>

 OperationResult<SignDocSESWithEsiaResult> SignReleaseStatement(Guid issueId); <.>

 OperationResult<string> SendRequestForValidation(Guid issueId); <.>

 OperationResult<string> DeleteCertificateIssueRequest(Guid issueId); <.>

 OperationResult<string> DownloadCertificateAndAssignToEmployee(Guid issueId, StaffEmployee employee); <.>

 OperationResult<KonturIssuesResponse> GetIssue(Guid issueId); <.>

 OperationResult<byte[]> GenerateRequestTemplate(Guid issueId, TemplateType templateType); <.>

 OperationResult<string> EditCertificateIssueRequest(Guid issueId, StaffEmployee employee); <.>

 OperationResult<string> GetEventList(int limit, string lastId); <.>

 OperationResult<string> SubjectIdentification(Guid issueId, StaffEmployee identifiedBy); <.>
}
----
<.> После подтверждения выпуска сертификата пользователем в кабинете Госуслуги, он будет выпущен
в {uc}. Загрузить выпущенный сертификат в карточку сотрудника нужно стандартным методом
`DownloadCertificateAndAssignToEmployee`. Подписание сертификатом {uc}
Подписание с помощью сервиса облачного подписания Контур осуществляется с помощью методов, определённых в сервисе `DocsVision.Kontur.DssService.ObjectModel.Services.IKonturDssService`.
<.> `IKonturIssuesService` -- сервис выпуска сертификатов Контур.
<.> `CreateCertificateIssue` -- создание заявки на выпуск сертификата.
+
.Параметры:
* `employee` -- сотрудник, для которого формируется сертификат.
* `inn` -- ИНН сотрудника.
+
<.> `AddDocumentRequisites` -- добавляет документы в заявку.
+
.Параметры:
* `issueId` -- ID заявки.
* `passData` -- паспортные данные.
+
<.> `SendDocumentScan` -- отправка скана документа.
+
.Параметры:
* `issueId` -- идентификатор запроса.
* `fileInfo` -- данные скана документа.
* `documentType` -- тип документа.
+
<.> `SendReleaseStatement` -- запрос на подтверждение операции.
+
.Параметры:
* `issueId` -- ID заявки.
+
<.> `SendReleaseStatementWithEsia` -- создает запрос на подтверждение через госуслуги.
+
.Параметры:
* `issueId` -- ID документа.
* `employee` -- сотрудник.
* `snils` -- СНИЛС сотрудника.
+
<.> `SignReleaseStatement` -- подпись заявления на выпуск сертификата НЭП.
+
.Параметры:
* `issueId` -- ID заявки.
* `smsCode` -- смс-код подтверждения.
+
<.> `SignReleaseStatement` -- подпись заявления на выпуск сертификата НЭП через госуслуги.
+
.Параметры:
* `issueId` -- ID заявки.
+
<.> `SendRequestForValidation` -- отправляет заявку на проверку.
+
.Параметры:
* `issueId` -- ID заявки.
+
<.> `DeleteCertificateIssueRequest` -- удаление заявки на сертификат.
+
.Параметры:
* `issueId` -- ID заявки.
+
<.> `DownloadCertificateAndAssignToEmployee` -- запрос файла сертификата УНЭП и загрузка его в карточку сотрудника.
+
.Параметры:
* `issueId` -- ID заявки.
* `employee` -- сотрудник, в карточку которого загружается сертификат.
Контур
+
<.> `GetIssue` -- запрос заявки на сертификат, проверка актуализации.
+
.Параметры:
* `issueId` -- ID заявки.
* `issueId` -- ID заявки.
+
<.> `GenerateRequestTemplate` -- генерация шаблона документа для заявления на выпуск сертификата.
+
.Параметры:
* `templateType` -- тип документа, получаемый от Контура.
+
<.> `EditCertificateIssueRequest` -- изменение заявки на сертификат.
+
.Параметры:
* `issueId` -- ID заявки.
+
<.> `GetEventList` -- запрос ленты событий заявок.
+
.Параметры:
* `limit` -- максимальное количество событий, которое нужно вернуть.
+
<.> `SubjectIdentification` -- отправляет заявку на проверку.
+
.Параметры:
* `issueId` -- ID заявки.
* `identifiedBy` -- сотрудник, который удостоверил личность.

== SendingFileInfo -- информация по файлу, отправляемому в УЦ Контур

Информация по файлу, отправляемому в УЦ Контур:

[source,csharp]
----
public class SendingFileInfo
    {
        public Guid FileId { get; set; } <.>
        public string Name { get; set; } <.>
        public long LongSize { get; set; } <.>
        public byte[] Data { get; set; } <.>

        public SendingFileInfo FromFileData(FileData fileData) <.>
        {
            return new SendingFileInfo
            {
                FileId = fileData.Id,
                Name = fileData.Name,
                LongSize = fileData.LongSize,
                Data = GetData(fileData)
            };
        }
----
<.> Идентификатор файла.
<.> Имя файла.
<.> Размер файла.
<.> Данные файла.
<.> Создаёт экземпляр `SendingFileInfo` по данным файла {dv}.

== DocumentType -- тип документа

[source,csharp]
----
	public enum DocumentType
    {
        Unknown, <.>
        Passport, <.>
        OtherIdentity, <.>
        Snils, <.>
        Egrul, <.>
        ManagementCompanyEgrul, <.>
        Egrip, <.>
        NaturalPersonInn, <.>
        SigningAuthority, <.>
        WarrantWithUseAreas, <.>
        ReleaseStatement, <.>
        ApplicantWarrant, <.>
        ApplicantPhoto, <.>
    }
----
<.> Может быть только возвращаемым типом.
<.> Паспорт РФ.
<.> Другой документ удостоверяющий личность.
<.> СНИЛС.
<.> Выписка из ЕГРЮЛ.
<.> Выписка из ЕГРЮЛ управляющей компании.
<.> Выписка из ЕГРИП.
<.> ИНН физического лица.
<.> Подтверждение права подписи.
<.> Доверенность с областями применения.
<.> Заявление на выпуск сертификата.
<.> Доверенность на получение.
<.> Фото обратившегося.

== IdentityDocument -- данные подтверждающего документа

[source,csharp]
----
    public class IdentityDocument
    {
        public DocumentType DocumentType { get; set; } <.>
		public string Series { get; set; } <.>
        public string Number { get; set; } <.>
        public string IssuerName { get; set; } <.>
        public string IssuerCode { get; set; } <.>
        public DateTime IssueDate { get; set; } <.>
    }
----
<.> Тип документа.
<.> Серия.
<.> Номер.
<.> Кем выдан.
<.> Код подразделения.
<.> Дата выдачи.

== TemplateType -- тип документа, получаемого от Контура

Предоставляет тип документа получаемого от Контура:

[source,csharp]
----
    public enum TemplateType
    {
        ReleaseStatement, <.>
        Receipt <.>
    }
}
----
<.> Заявление на выпуск сертификата.
<.> Расписка о том, что сертификат выпущен.

== IKonturDssService -- сервис подписания Контур

[source,csharp]
----
    public interface IKonturDssService
    {
        OperationResult<KonturSignResponse> SignDocument(SignRequest request, StaffEmployee employee); <.>
        OperationResult<DssSignStatusResponse> GetStatus(Guid operationId); <.>
        OperationResult<DssConfirmationResponse> ConfirmSignOperation(Guid operationId, string confirmationCode); <.>
        OperationResult<byte[]> GetResult(Guid resultId); <.>
    }
----
<.> Подписывает файлы документа.
<.> Возвращает статус подписания.
<.> Подтверждает операцию подписания.
<.> Возвращает сформированную подпись.

== SignRequest -- данные для подписания

[source,csharp]
----
    public class SignRequest
    {
        public Guid DocumentId { get; set; }
        public DocumentSignaturePartInfo[] Parts { get; set; }
        public DssSignRequestSignature Signature { get; set; }
    }
----

== DocumentSignaturePartInfo -- подписываемая часть документа

[source,csharp]
----
    public class DocumentSignaturePartInfo
    {
        public SignatureItemType PartType { get; set; }
        public Guid? FileId { get; set; }
    }
----

== KonturSignResponse --  ответ на запрос регистрации

Ответ на запрос регистрации операции подписания

[source,csharp]
----
    public class KonturSignResponse
    {
        public Guid OperationId { get; set; } <.>
        public ConfirmType ConfirmType { get; set; } <.>
        public string PhoneLastNumbers { get; set; } <.>
        public AdditionalDssInfo AdditionalDssInfo { get; set; } <.>
    }
----
<.> Идентификатор операции.
<.> Способ подтверждения операции.
<.> Последние 4 цифры номера телефона пользователя. Передаётся при подтверждении операции через СМС или с помощью Applet на SIM-карте.
<.> Дополнительная информация для DSS-сертификата.

== DssSignStatusResponse -- статус выполнения операции подписания

[source,csharp]
----
    public class DssSignStatusResponse
    {
        public DssSignStatus SignStatus { get; set; } <.>
        public List<FileStatus> FileStatuses { get; set; } = new List<FileStatus>(); <.>
    }
----
<.> Статус подписания.
<.> Статусы подписания частей запроса на подписание.

== DssSignStatus -- статус подписания

[source,csharp]
----
    public enum DssSignStatus
    {
        Unknown = 0, <.>
        WaitingUser = 1, <.>
        InProgress = 2, <.>
        Complete = 3, <.>
        Error = 4 <.>
    }
----
<.> Неизвестно.
<.> Ожидает действия (подтверждения) пользователя.
<.> В процессе подписания.
<.> Завершено.
<.> Завершено с ошибкой.
