= Создание заявки на выпуск сертификата

// Сообщения о необходимых операциях с МЧД, например, операции регистрации, записываются в _Карточку сообщений {of-mk}_.

Надо учитывать, что выпуск будет выполняться по 2 вариантам: 1) с использование личного кабинета ДВ (общий для всех заказчиков, выбравших такой вариант) и 2) с использованием личного кабинета заказчика.

Последний выпущенный на сотрудника облачный сертификат надо записывать в поле Certificate секции MainInfo карточки настроек пользователя (UserProfileCard). При выпуске нового старый сертификат удалять из данного поля.

Должна быть возможность работать с облачной подписью через диалог выбора сертификата:

должна быть возможность добавления облачной в профиле пользователя;
должна быть возможность выбора облачной подписи при подписании.

Требуется проверять лицензию Docsvision на Модуль интеграции с УЦ Контур: 1) при выпуске сертификата (в первом по порядку методе API Docsvision); 2) при подписании документов (на том же шаге, как с КриптоПро).
